#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

PACKAGE_NAME="${PACKAGE_NAME:-pantheongpu}"
VERSION="${VERSION:-$(tr -d '[:space:]' < VERSION)}"
ARCH="${ARCH:-amd64}"
RELEASE_ROOT="${RELEASE_ROOT:-release}"
APP_DIR="${APP_DIR:-${RELEASE_ROOT}/pantheon-${VERSION}}"
DIST_DIR="${DIST_DIR:-dist}"
BUNDLE_NAME="${PACKAGE_NAME}_${VERSION}_${ARCH}"
BUNDLE_DIR="${DIST_DIR}/${BUNDLE_NAME}"
DEB_PATH="${DIST_DIR}/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
TAR_PATH="${DIST_DIR}/${BUNDLE_NAME}.tar.gz"
ZIP_PATH="${DIST_DIR}/${BUNDLE_NAME}.zip"
BUILD_BINARY="${BUILD_BINARY:-1}"

BUILD_BINARY="${BUILD_BINARY}" VERSION="${VERSION}" ARCH="${ARCH}" DIST_DIR="${DIST_DIR}" RELEASE_ROOT="${RELEASE_ROOT}" APP_DIR="${APP_DIR}" "${SCRIPT_DIR}/build_deb.sh"

if [ ! -f "${DEB_PATH}" ]; then
    echo "Missing Debian package: ${DEB_PATH}" >&2
    exit 1
fi

rm -rf "${BUNDLE_DIR}" "${TAR_PATH}" "${ZIP_PATH}"
mkdir -p "${BUNDLE_DIR}/bin" "${BUNDLE_DIR}/packages" "${BUNDLE_DIR}/docs"

install -m 0755 "${APP_DIR}/pantheon" "${BUNDLE_DIR}/bin/pantheon"
install -m 0644 "${DEB_PATH}" "${BUNDLE_DIR}/packages/$(basename "${DEB_PATH}")"
install -m 0644 VERSION "${BUNDLE_DIR}/VERSION"
install -m 0644 LICENSE "${BUNDLE_DIR}/LICENSE"
install -m 0644 packaging/RELEASE_README.md "${BUNDLE_DIR}/README.md"
install -m 0644 RELEASE_NOTES.md "${BUNDLE_DIR}/RELEASE_NOTES.md"
install -m 0644 docs/release_process.md "${BUNDLE_DIR}/docs/release_process.md"
install -m 0644 packaging/INSTALL.md "${BUNDLE_DIR}/INSTALL.md"

cat > "${BUNDLE_DIR}/install.sh" <<'EOF'
#!/usr/bin/env sh
set -eu

script_dir=$(CDPATH= cd "$(dirname "$0")" && pwd)
cd "${script_dir}"

prefix="${PREFIX:-/opt/pantheongpu}"
bindir="${BINDIR:-/usr/local/bin}"

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root, for example: sudo ./install.sh" >&2
    exit 1
fi

case "${prefix}" in
    /*) ;;
    *) echo "PREFIX must be an absolute path: ${prefix}" >&2; exit 1 ;;
esac
case "${bindir}" in
    /*) ;;
    *) echo "BINDIR must be an absolute path: ${bindir}" >&2; exit 1 ;;
esac
case "${prefix}" in
    /) echo "Refusing unsafe PREFIX: ${prefix}" >&2; exit 1 ;;
esac
case "${bindir}" in
    /) echo "Refusing unsafe BINDIR: ${bindir}" >&2; exit 1 ;;
esac

launcher="${bindir}/pantheon"
target="${prefix}/bin/pantheon"
legacy_line="exec ${target} \"\$@\""

if [ "${launcher}" = "${target}" ]; then
    echo "BINDIR must not resolve to the Pantheon binary directory." >&2
    exit 1
fi

if [ -L "${launcher}" ]; then
    if [ "$(readlink "${launcher}")" = "${target}" ]; then
        rm -f "${launcher}"
    else
        echo "Refusing to replace existing symlink: ${launcher}" >&2
        exit 1
    fi
elif [ -e "${launcher}" ]; then
    # Upgrade the legacy wrapper generated by earlier Pantheon bundles, but
    # never overwrite another program's command.
    if [ -f "${launcher}" ] && grep -Fqx "${legacy_line}" "${launcher}"; then
        rm -f "${launcher}"
    else
        echo "Refusing to replace existing command: ${launcher}" >&2
        exit 1
    fi
fi

mkdir -p "${prefix}/bin" "${bindir}"
install -m 0755 bin/pantheon "${target}"
ln -s "${target}" "${launcher}"
echo "Pantheon GPU installed. Try: pantheon --test baseline_metrics --duration 10"
EOF
chmod 0755 "${BUNDLE_DIR}/install.sh"

cat > "${BUNDLE_DIR}/uninstall.sh" <<'EOF'
#!/usr/bin/env sh
set -eu

prefix="${PREFIX:-/opt/pantheongpu}"
bindir="${BINDIR:-/usr/local/bin}"

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root, for example: sudo ./uninstall.sh" >&2
    exit 1
fi

case "${prefix}" in
    /*) ;;
    *) echo "PREFIX must be an absolute path: ${prefix}" >&2; exit 1 ;;
esac
case "${bindir}" in
    /*) ;;
    *) echo "BINDIR must be an absolute path: ${bindir}" >&2; exit 1 ;;
esac
case "${prefix}" in
    /) echo "Refusing unsafe PREFIX: ${prefix}" >&2; exit 1 ;;
esac
case "${bindir}" in
    /) echo "Refusing unsafe BINDIR: ${bindir}" >&2; exit 1 ;;
esac

launcher="${bindir}/pantheon"
target="${prefix}/bin/pantheon"
legacy_line="exec ${target} \"\$@\""
if [ -L "${launcher}" ] && [ "$(readlink "${launcher}")" = "${target}" ]; then
    rm -f "${launcher}"
elif [ -f "${launcher}" ] && grep -Fqx "${legacy_line}" "${launcher}"; then
    rm -f "${launcher}"
fi
rm -rf "${prefix}"

uninstall_user=${SUDO_USER:-}
if [ -n "${PANTHEON_UNINSTALL_HOME:-}" ]; then
    uninstall_home=${PANTHEON_UNINSTALL_HOME}
elif [ -n "${uninstall_user}" ] && [ "${uninstall_user}" != root ] &&
    command -v getent >/dev/null 2>&1; then
    uninstall_home=$(getent passwd "${uninstall_user}" | cut -d: -f6)
else
    uninstall_home=${HOME:-/root}
fi

cache_home=${PANTHEON_CACHE_HOME:-"${uninstall_home}/.cache"}
rm -rf "${cache_home}/pantheongpu"

echo "Pantheon GPU and the current user's workload cache were removed."
EOF
chmod 0755 "${BUNDLE_DIR}/uninstall.sh"

(
    cd "${DIST_DIR}"
    tar -czf "$(basename "${TAR_PATH}")" "${BUNDLE_NAME}"
)

if command -v zip >/dev/null 2>&1; then
    (cd "${DIST_DIR}" && zip -qr "$(basename "${ZIP_PATH}")" "${BUNDLE_NAME}")
else
    python3 - <<PY
import shutil
shutil.make_archive("${ZIP_PATH%.zip}", "zip", "${DIST_DIR}", "${BUNDLE_NAME}")
PY
fi

echo "Created ${DEB_PATH}"
echo "Created ${TAR_PATH}"
echo "Created ${ZIP_PATH}"
